site_name: Jypyter Sketcher
nav:
    - Home: index.md
    - About: about.md
    - Definition: sketcher.md
    - Reference: reference.md
theme:
  name: material
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'    