site_name: Jypyter Sketcher
nav:
    - Home: index.md
    - About: about.md
    - Presentation: presentation.md
    - Learning by Example: sketcher.md
    - Shapes Reference: shapereference.md
theme:
  name: material
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
plugins:
    - search  